namespace TrilhaCsharpDotnetSenior.Models;

public sealed record Lesson(
    string Title,
    string Summary,
    IReadOnlyList<string> Objectives,
    IReadOnlyList<string> PracticeTasks,
    string CodeExample,
    string? Scenario = null,
    string? Resolution = null);

public sealed record SelfCheck(string Question, IReadOnlyList<string> Options, int CorrectOption, string Explanation);

public sealed record LearningModule(
    int Number,
    string Slug,
    string Title,
    string Kicker,
    string Description,
    string Duration,
    string Icon,
    IReadOnlyList<Lesson> Lessons,
    SelfCheck SelfCheck,
    string Track = "professional");

public sealed record LearningTrack(string Slug, string Title, string Description);

public static class LearningCatalog
{
    public static IReadOnlyList<LearningTrack> Tracks { get; } =
    [
        new("fast-track", "Fast track: júnior ao pleno", "A base essencial para escrever código confiável, entregar APIs e trabalhar bem em um time."),
        new("professional", "Trilha profissional", "Aprofunde runtime, design, web, dados, qualidade e sistemas distribuídos."),
        new("architecture", "Arquitetura e design", "Aprenda a escolher arquiteturas e patterns a partir do problema, não da moda.")
    ];

    public static IReadOnlyList<LearningModule> Modules { get; } =
    [
        new(
            1,
            "fast-track-junior-pleno",
            "Fast track: júnior ao pleno",
            "Base essencial",
            "Uma sequência curta para consolidar o que um profissional júnior precisa dominar e o que diferencia uma atuação plena.",
            "2 semanas",
            "FT",
            [
                new("Como o código roda", "Tipos, memória, coleções e exceções para raciocinar sobre o comportamento do programa.",
                    ["Escolher tipos e coleções adequados", "Explicar nullability e invariantes", "Ler uma exceção até a causa raiz"],
                    ["Modele um pedido sem estados inválidos", "Compare List, HashSet e Dictionary", "Escreva um tratamento que preserve a causa original"],
                    "public sealed record Order(Guid Id, decimal Total, OrderStatus Status);\n\nif (order.Total <= 0)\n    throw new ArgumentOutOfRangeException(nameof(order));"),
                new("Async, HTTP e APIs", "O mínimo de web para construir endpoints previsíveis e não bloquear trabalho de I/O.",
                    ["Propagar CancellationToken", "Diferenciar status codes", "Validar entrada na borda"],
                    ["Adicione timeout a uma chamada HTTP", "Modele respostas 200, 400, 404 e 409", "Descreva o contrato de um endpoint de criação"],
                    "app.MapGet(\"/orders/{id:guid}\", async (Guid id, IOrderReader reader, CancellationToken ct) =>\n{\n    var order = await reader.FindAsync(id, ct);\n    return order is null ? Results.NotFound() : Results.Ok(order);\n});"),
                new("Dados e estado", "SQL, transações e concorrência para que a aplicação não perca nem duplique informação.",
                    ["Ler uma consulta simples", "Definir uma fronteira transacional", "Projetar uma operação idempotente"],
                    ["Escolha índices para uma busca de pedidos", "Desenhe o fluxo de pagamento repetido", "Explique quando consistência eventual é aceitável"],
                    "await using var transaction = await db.Database.BeginTransactionAsync(ct);\nawait db.SaveChangesAsync(ct);\nawait transaction.CommitAsync(ct);"),
                new("Testes e depuração", "Feedback rápido, logs úteis e investigação disciplinada de falhas.",
                    ["Testar uma regra isolada", "Separar causa de sintoma", "Adicionar contexto sem vazar dados"],
                    ["Cubra uma regra de desconto", "Reproduza um bug com um teste", "Transforme uma mensagem em log estruturado"],
                    "[Fact]\npublic void Discount_never_goes_below_zero()\n{\n    Assert.Equal(0m, Discount.Apply(10m, 1.5m));\n}"),
                new("Entrega profissional", "Git, revisão, comunicação e pequenos designs que tornam o trabalho previsível.",
                    ["Fazer commits revisáveis", "Explicar trade-offs em uma PR", "Dividir trabalho em incrementos seguros"],
                    ["Escreva uma checklist de PR", "Proponha um rollout com rollback", "Registre uma decisão curta em um ADR"],
                    "public sealed record Decision(string Context, string Choice, string Consequence);"),
            ],
            new("Qual comportamento mais caracteriza uma entrega de nível pleno?", ["Explicitar trade-offs e reduzir risco", "Escrever a maior quantidade de código", "Evitar testes para ganhar velocidade", "Decidir sozinho sem comunicar"], 0, "Profissionais plenos conectam implementação, risco e impacto; eles tornam as decisões compreensíveis e reversíveis."),
            "fast-track"),
        new(
            2,
            "fundamentos-runtime",
            "C# e o runtime",
            "Base sólida",
            "Domine tipos, fluxo, memória, async/await e as decisões do runtime que sustentam aplicações confiáveis.",
            "3 semanas",
            "01",
            [
                new("C# moderno sem mágica", "Da tipagem estática às expressões e pattern matching que deixam o código explícito.",
                    ["Escolher tipos e imutabilidade com intenção", "Ler LINQ sem esconder complexidade", "Diferenciar stack, heap e alocações comuns"],
                    ["Modele um parser de comandos com records", "Compare uma solução LINQ com um loop explícito", "Meça uma alocação usando BenchmarkDotNet conceitualmente"],
                    "public sealed record Money(decimal Amount, string Currency);\n\npublic static Money Add(Money left, Money right)\n{\n    if (left.Currency != right.Currency)\n        throw new ArgumentException(\"Currencies must match.\");\n\n    return left with { Amount = left.Amount + right.Amount };\n}"),
                new("Concorrência e assíncrono", "Aprenda a propagar cancelamento e a evitar bloqueios em I/O.",
                    ["Usar CancellationToken como parte do contrato", "Distinguir concorrência de paralelismo", "Evitar async void e bloqueios com Result"],
                    ["Adicione timeout a um cliente HTTP", "Escreva um pipeline que cancele ao fechar a requisição", "Explique por que Task.Run não torna I/O mais rápido"],
                    "public async Task<IReadOnlyList<Order>> LoadAsync(\n    CancellationToken cancellationToken)\n{\n    return await repository.GetOpenOrdersAsync(cancellationToken);\n}"),
                new("Ferramentas do runtime", "GC, exceções, logging e diagnóstico para raciocinar com evidências.",
                    ["Ler um stack trace e localizar a causa", "Diferenciar exceções recuperáveis de bugs", "Escolher logs estruturados"],
                    ["Faça um plano de investigação para uma latência crescente", "Converta logs interpolados em logs estruturados", "Desenhe uma política de retry com limites"],
                    "logger.LogInformation(\n    \"Order {OrderId} processed in {ElapsedMs} ms\",\n    order.Id, stopwatch.ElapsedMilliseconds);"),
            ],
            new("Qual recurso deve ser propagado até a camada de I/O?", ["CancellationToken", "Thread.CurrentThread", "Console.Out", "GCHandle"], 0, "O CancellationToken torna cancelamento parte do contrato e evita trabalho inútil quando a requisição termina.")),
        new(
            3,
            "oop-design",
            "Orientação a objetos e design",
            "Decisões melhores",
            "Transforme requisitos em modelos coesos, interfaces pequenas e componentes que aceitam mudança sem medo.",
            "3 semanas",
            "02",
            [
                new("Abstração que protege regras", "Entidades, value objects e invariantes mantidas no lugar certo.",
                    ["Separar identidade de valor", "Proteger invariantes no construtor", "Evitar anemic models quando regras importam"],
                    ["Modele um carrinho que nunca aceita quantidade negativa", "Extraia um EmailAddress com validação", "Escreva três invariantes antes de criar classes"],
                    "public sealed class EmailAddress\n{\n    public string Value { get; }\n\n    public EmailAddress(string value)\n    {\n        if (!value.Contains('@'))\n            throw new ArgumentException(\"Invalid email.\");\n\n        Value = value.Trim().ToLowerInvariant();\n    }\n}"),
                new("SOLID em contexto", "Use princípios como heurísticas, não como uma coleção de abstrações obrigatórias.",
                    ["Identificar acoplamento concreto", "Compor políticas via injeção de dependência", "Reconhecer quando uma interface é prematura"],
                    ["Refatore um serviço com três motivos de mudança", "Defina uma interface focada para cobrança", "Liste o custo de uma abstração que não evolui"],
                    "public interface IClock\n{\n    DateTimeOffset UtcNow { get; }\n}"),
                new("Padrões e arquitetura", "Escolha padrões porque reduzem risco no domínio, não porque são populares.",
                    ["Distinguir composição de herança", "Usar Strategy e Decorator com propósito", "Mapear fronteiras entre domínio e infraestrutura"],
                    ["Troque um switch de regras por uma estratégia", "Desenhe uma fronteira hexagonal para pedidos", "Explique qual acoplamento você aceitou"],
                    "public sealed class DiscountPipeline(IEnumerable<IDiscountRule> rules)\n{\n    public decimal Apply(decimal total) =>\n        rules.Aggregate(total, (current, rule) => rule.Apply(current));\n}"),
            ],
            new("Qual é o melhor primeiro passo ao extrair uma abstração?", ["Identificar uma variação real e seu contrato", "Criar uma interface para toda classe", "Duplicar os métodos antes de decidir", "Esconder todos os campos"], 0, "Abstrações devem proteger uma variação ou fronteira real; interfaces universais aumentam acoplamento.")),
        new(
            4,
            "aspnet-web-apis",
            "ASP.NET Core e Web APIs",
            "Interfaces públicas",
            "Construa APIs HTTP previsíveis, observáveis e fáceis de evoluir, com validação, DI e contratos claros.",
            "4 semanas",
            "03",
            [
                new("Pipeline e endpoints", "Entenda middleware, roteamento, filtros e o ciclo de uma requisição.",
                    ["Ordenar middleware com segurança", "Modelar respostas HTTP coerentes", "Aplicar ProblemDetails em falhas"],
                    ["Mapeie o pipeline de uma requisição POST", "Defina status codes para quatro cenários", "Adicione correlação a uma resposta"],
                    "app.MapGet(\"/orders/{id:guid}\", async (Guid id, IOrderReader reader, CancellationToken ct) =>\n{\n    var order = await reader.FindAsync(id, ct);\n    return order is null ? Results.NotFound() : Results.Ok(order);\n});"),
                new("Contratos e validação", "Requests, responses e compatibilidade evolutiva.",
                    ["Separar DTOs de entidades", "Validar na borda e no domínio", "Versionar sem quebrar consumidores"],
                    ["Crie um DTO de criação sem campos calculados", "Escreva um ProblemDetails para validação", "Planeje uma mudança compatível"],
                    "public sealed record CreateOrderRequest(\n    Guid CustomerId,\n    IReadOnlyList<CreateOrderLine> Lines);"),
                new("Segurança web", "Autenticação, autorização, segredos e ameaças comuns.",
                    ["Diferenciar autenticação de autorização", "Evitar confiar em dados do cliente", "Aplicar princípio do menor privilégio"],
                    ["Modele políticas por capacidade", "Faça uma revisão OWASP de um endpoint", "Liste segredos que nunca devem ir para o repositório"],
                    "[Authorize(Policy = Policies.OrdersRead)]\npublic sealed class OrdersController : ControllerBase\n{\n    // Keep authorization close to the use case boundary.\n}"),
            ],
            new("Onde uma regra de autorização por capacidade deve ser aplicada?", ["Em uma policy no boundary da aplicação", "Somente no JavaScript", "Apenas no banco", "Em um comentário no endpoint"], 0, "Policies e handlers no boundary server-side garantem que a decisão não dependa do cliente.")),
        new(
            5,
            "dados-persistencia",
            "Dados e persistência",
            "Estado confiável",
            "Modele transações, consultas e evolução de esquema pensando em consistência, custo e recuperação.",
            "3 semanas",
            "04",
            [
                new("SQL e modelagem", "Chaves, índices e consultas que deixam intenção e custo visíveis.",
                    ["Escolher cardinalidade e índices", "Ler um plano de execução", "Evitar N+1 em consultas"],
                    ["Modele pedidos e itens com integridade", "Justifique dois índices", "Reescreva uma consulta N+1"],
                    "public sealed record OrderSummary(Guid Id, decimal Total, int ItemCount);\n\n// Keep projections narrow when a read model does not need the aggregate.\nvar summaries = await db.Orders\n    .Select(order => new OrderSummary(order.Id, order.Total, order.Items.Count))\n    .ToListAsync(cancellationToken);"),
                new("Transações e consistência", "Escolha fronteiras de transação e aceite consistência eventual conscientemente.",
                    ["Definir unidade de trabalho", "Reconhecer conflitos de concorrência", "Planejar idempotência"],
                    ["Desenhe um fluxo idempotente de pagamento", "Explique onde uma transação termina", "Crie uma estratégia de retry segura"],
                    "await using var transaction = await db.Database\n    .BeginTransactionAsync(cancellationToken);\n\n// Write the aggregate and its outbox message atomically.\nawait db.SaveChangesAsync(cancellationToken);\nawait transaction.CommitAsync(cancellationToken);"),
                new("Cache e evolução", "Cache-aside, invalidação e migrações reversíveis.",
                    ["Calcular o custo de um cache stale", "Planejar migrações expand/contract", "Evitar cachear dados sensíveis"],
                    ["Defina TTL por tipo de dado", "Planeje uma migração sem downtime", "Documente o que acontece após um cache miss"],
                    "var cached = await cache.GetStringAsync(key, cancellationToken);\nif (cached is not null)\n    return JsonSerializer.Deserialize<Order>(cached);\n\nvar fresh = await reader.LoadAsync(id, cancellationToken);"),
            ],
            new("Qual propriedade uma operação de reprocessamento precisa ter?", ["Idempotência", "Aleatoriedade", "Acoplamento", "Estado global"], 0, "Idempotência permite repetir uma operação sem produzir efeitos duplicados quando há retries ou mensagens repetidas.")),
        new(
            6,
            "qualidade-observabilidade",
            "Testes, qualidade e observabilidade",
            "Confiança para mudar",
            "Crie feedback rápido com testes no nível certo, telemetria útil e uma definição objetiva de qualidade.",
            "3 semanas",
            "05",
            [
                new("Pirâmide de testes", "Unidade, integração e contrato: cada camada responde uma pergunta diferente.",
                    ["Escolher o menor teste que prova o comportamento", "Evitar mocks que duplicam implementação", "Testar bordas e falhas"],
                    ["Escreva casos para uma regra de desconto", "Transforme um teste frágil em teste de contrato", "Separe teste de integração de unidade"],
                    "[Fact]\npublic void Discount_is_capped_at_zero()\n{\n    var result = Discount.Apply(total: 10m, percentage: 1.5m);\n\n    Assert.Equal(0m, result);\n}"),
                new("Observabilidade prática", "Métricas, logs e traces para responder o que aconteceu.",
                    ["Definir SLI e SLO", "Usar correlação sem vazar dados", "Investigar com sinais combinados"],
                    ["Escolha três métricas de uma API", "Escreva um alerta acionável", "Faça um roteiro de incidente"],
                    "using var activity = source.StartActivity(\"orders.read\");\nactivity?.SetTag(\"order.id\", orderId);\nlogger.LogInformation(\"Reading order {OrderId}\", orderId);"),
                new("Entrega e qualidade", "Automação, revisão e feedback como partes do produto.",
                    ["Definir gates que protegem sem bloquear", "Revisar risco de uma mudança", "Documentar decisões"],
                    ["Escreva uma checklist de PR", "Defina um gate de cobertura com contexto", "Registre uma decisão arquitetural"],
                    "public sealed class HealthPolicy\n{\n    public bool IsReady(bool databaseReady, bool dependenciesReady) =>\n        databaseReady && dependenciesReady;\n}"),
            ],
            new("Qual pergunta um teste de unidade deve responder?", ["Uma regra isolada funciona para seus cenários?", "O cluster está saudável?", "Qual é o custo do cloud?", "Quem aprovou o PR?"], 0, "Testes de unidade dão feedback rápido sobre comportamento isolado; saúde e custo pertencem a outros sinais.")),
        new(
            7,
            "distribuidos-seguranca-performance-lideranca",
            "Distribuídos, segurança, performance e liderança",
            "Visão sistêmica",
            "Conecte sistemas, pessoas e trade-offs: resiliência, performance e influência técnica orientada a impacto.",
            "4 semanas",
            "06",
            [
                new("Sistemas distribuídos", "Mensageria, resiliência e consistência quando a rede falha.",
                    ["Projetar consumidores idempotentes", "Usar timeout, retry e circuit breaker com limites", "Distinguir fila de stream"],
                    ["Modele uma outbox e um consumidor", "Defina backoff com jitter", "Descreva o comportamento após uma partição"],
                    "public async Task HandleAsync(OrderPlaced message, CancellationToken ct)\n{\n    if (await store.HasProcessedAsync(message.Id, ct))\n        return;\n\n    await store.ApplyAsync(message, ct);\n    await store.MarkProcessedAsync(message.Id, ct);\n}"),
                new("Performance e segurança", "Otimize o caminho crítico sem negociar proteção de dados.",
                    ["Medir antes de otimizar", "Reconhecer gargalos de CPU, I/O e memória", "Aplicar threat modeling"],
                    ["Faça um orçamento de latência", "Liste ameaças de um fluxo de upload", "Defina dados que precisam ser criptografados"],
                    "public sealed record PerformanceBudget(\n    TimeSpan P95Latency,\n    long MaxAllocatedBytes,\n    int MaxDatabaseRoundTrips);"),
                new("Liderança técnica", "Multiplique qualidade por alinhamento, escrita e decisões reversíveis.",
                    ["Comunicar trade-offs para diferentes públicos", "Facilitar uma decisão sem impor solução", "Criar uma estratégia incremental"],
                    ["Escreva um ADR com duas opções", "Prepare uma revisão de incidente sem culpa", "Transforme uma visão em milestones"],
                    "public sealed record Decision(\n    string Context,\n    string Choice,\n    IReadOnlyList<string> Consequences);"),
            ],
            new("Qual combinação é mais segura para chamadas entre serviços?", ["Timeout, retry limitado e idempotência", "Retry infinito sem timeout", "Ignorar erros de rede", "Compartilhar banco sem contrato"], 0, "Falhas devem ter limites e operações repetíveis; timeout, retry limitado e idempotência trabalham juntos."))
        ,new(
            8,
            "arquitetura-por-cenarios",
            "Arquitetura por cenários",
            "Decisões contextualizadas",
            "Aprenda a começar pelo cenário, explicitar restrições e escolher uma arquitetura que resolva o problema com o menor risco.",
            "3 semanas",
            "08",
            [
                new("Monólito modular", "Escolha um limite de simplicidade operacional antes de distribuir o sistema.",
                    ["Reconhecer quando simplicidade operacional é uma vantagem", "Separar módulos sem criar rede prematuramente", "Definir regras de dependência entre contextos"],
                    ["Desenhe módulos de pedidos, faturamento e catálogo", "Bloqueie uma referência direta entre módulos", "Liste o sinal que justificaria extrair um serviço depois"],
                    "public sealed class OrdersModule(IOrderStore store)\n{\n    public Task<Order> PlaceAsync(PlaceOrder command, CancellationToken ct)\n        => store.AddAsync(command, ct);\n}",
                    "Um time de quatro pessoas precisa entregar mudanças frequentes e não tem operação 24x7.",
                    "Um monólito modular reduz latência organizacional e custo operacional; módulos bem delimitados preservam uma futura extração."),
                new("Eventos e outbox", "Garanta entrega confiável quando uma operação precisa mudar o banco e publicar uma mensagem.",
                    ["Explicar por que dual write perde mensagens", "Projetar outbox e reprocessamento", "Definir idempotência e observabilidade do consumidor"],
                    ["Modele estados da outbox", "Defina a chave de idempotência do pagamento", "Descreva o que acontece após uma queda do broker"],
                    "await db.SaveChangesAsync(ct);\nawait outbox.EnqueueAsync(new OrderPlaced(order.Id), ct);\nawait transaction.CommitAsync(ct);",
                    "O pedido não pode desaparecer mesmo que o broker fique indisponível no momento da confirmação.",
                    "A outbox torna a mudança de estado e a intenção de publicação atômicas; um worker publica depois e consumidores repetíveis toleram retries."),
                new("CQRS e leitura", "Separe modelos quando escrita transacional e leitura analítica têm necessidades incompatíveis.",
                    ["Distinguir separação de modelos de dois bancos obrigatórios", "Escolher projeções para consultas", "Comunicar o atraso aceitável ao produto"],
                    ["Modele uma projeção de pedidos", "Defina um SLO de atualização do painel", "Liste telas que não podem ser eventualmente consistentes"],
                    "public sealed record OrderSummary(Guid Id, string Status, decimal Total);\n\npublic Task<IReadOnlyList<OrderSummary>> SearchAsync(string query, CancellationToken ct)\n    => readDb.SearchAsync(query, ct);",
                    "A equipe precisa de consultas flexíveis sem colocar relatórios pesados no caminho transacional.",
                    "Uma projeção especializada deixa cada modelo eficiente e torna o trade-off de consistência explícito para quem consome a informação.")
            ],
            new("Qual é o primeiro passo de uma decisão arquitetural?", ["Descrever o cenário, restrições e forças", "Escolher microserviços por padrão", "Selecionar uma biblioteca", "Copiar a arquitetura de outra empresa"], 0, "Arquitetura é uma resposta a forças do cenário; sem restrições explícitas, a solução vira preferência pessoal."),
            "architecture"),
        new(
            9,
            "design-patterns-na-pratica",
            "Design patterns na prática",
            "Padrões com propósito",
            "Use patterns como vocabulário para mudanças recorrentes, mantendo o foco no problema e no custo da abstração.",
            "2 semanas",
            "09",
            [
                new("Strategy e Factory", "Isole famílias de algoritmos que mudam com frequência e precisam ser escolhidos em runtime.",
                    ["Identificar uma família de algoritmos", "Compor estratégias por injeção", "Evitar uma Factory que vire um switch gigante"],
                    ["Implemente frete nacional e internacional", "Defina o contrato de uma estratégia", "Escolha o limite em que configuração substitui código"],
                    "public interface IShippingStrategy\n{\n    Money Calculate(Shipment shipment);\n}\n\npublic sealed class ShippingCalculator(IEnumerable<IShippingStrategy> strategies)\n{\n    public Money Calculate(Shipment shipment)\n        => strategies.Single(x => x.CanHandle(shipment)).Calculate(shipment);\n}",
                    "O cálculo de frete muda por região e transportadora, com regras novas todos os meses.",
                    "Strategy mantém cada algoritmo isolado e Factory ou composição escolhe a regra sem espalhar condicionais pelo caso de uso."),
                new("Decorator e Adapter", "Adicione comportamento transversal e integre contratos legados sem contaminar o caso de uso.",
                    ["Separar comportamento transversal do caso de uso", "Encapsular uma API legada", "Evitar decorar tudo sem medir o custo"],
                    ["Adicione métricas a um gateway", "Adapte um provedor que usa callbacks", "Defina quais retries são seguros"],
                    "public sealed class MeasuredPaymentGateway(IPaymentGateway inner, IMeter meter) : IPaymentGateway\n{\n    public async Task<PaymentResult> PayAsync(Payment payment, CancellationToken ct)\n    {\n        using var timer = meter.StartTimer(\"payment\");\n        return await inner.PayAsync(payment, ct);\n    }\n}",
                    "O gateway precisa de métricas e retry, mas o provedor legado expõe um contrato incompatível.",
                    "Decorator adiciona comportamento transversal e Adapter traduz a API externa; o caso de uso continua dependente de um contrato estável."),
                new("Observer e Mediator", "Coordene reações independentes a um fato de domínio sem acoplar o núcleo às integrações.",
                    ["Distinguir evento de comando", "Manter handlers independentes", "Definir consistência e falhas de cada reação"],
                    ["Modele OrderConfirmed", "Defina a política de retry do e-mail", "Explique quando usar uma fila em vez de evento síncrono"],
                    "public sealed record OrderConfirmed(Guid OrderId);\n\npublic sealed class AuditHandler(IAuditLog log)\n{\n    public Task HandleAsync(OrderConfirmed message, CancellationToken ct)\n        => log.AppendAsync(message.OrderId, ct);\n}",
                    "Confirmar um pedido precisa atualizar estoque, enviar e-mail e registrar auditoria sem acoplar o domínio a cada integração.",
                    "Um evento de domínio publica o fato e handlers independentes reagem; um mediator organiza comandos sem transformar o núcleo em um coordenador de infraestrutura.")
            ],
            new("Quando um design pattern é uma boa escolha?", ["Quando nomeia e reduz uma complexidade recorrente", "Quando adiciona classes por precaução", "Quando elimina todo acoplamento", "Quando substitui testes"], 0, "Um pattern vale quando torna uma mudança recorrente mais explícita e barata; sua forma não é um objetivo isolado."),
            "architecture")
    ];

    public static LearningModule? Find(string slug) => Modules.FirstOrDefault(module => module.Slug.Equals(slug, StringComparison.OrdinalIgnoreCase));
}
